stages:
  - test

cypress:
  stage: test
  image: cypress/browsers:node18.12.0-chrome106-ff106
  script:
    - cd frontend # Change to the frontend directory where your Cypress tests are located
    - npm install --legacy-peer-deps
    - npx cypress run # This command will run all Cypress tests in headless mode
  
