stages:
  - test

cypress:
  stage: test
  image: node:16.5.0
  script:
    - apt-get update && apt-get install -y xvfb chromium 
    - Xvfb :99 -ac -screen 0 1280x1024x16 &
    - export DISPLAY=:99
    - cd frontend # Change to the frontend directory where your Cypress tests are located
    - npm install --legacy-peer-deps
    - npm start &
    - npx cypress run --browser chrome