stages:
  - test

cypress:
  stage: test
  image: node:16.5.0
  script:
    - apt-get update && apt-get install -y chromium firefox
    - cd frontend # Change to the frontend directory where your Cypress tests are located
    - npm install --legacy-peer-deps
    - npm start &
    - npx cypress run --browser chrome
