stages:
  - test

cypress:
  stage: test
  image: cypress/browsers:node18.12.0-chrome106-ff106
  script:
    - cd frontend # Change to the frontend directory where your Cypress tests are located
    - npm install --legacy-peer-deps
    - npm start &
    - npx cypress run --browser chrome