stages:
  - test

cypress:
  stage: test
  image: cypress/browsers:node16.5.0-chrome94-ff93
  script:
    - cd frontend # Change to the frontend directory where your Cypress tests are located
    - npm install --legacy-peer-deps
    - npm start 
    - npx cypress run & # This command will run all Cypress tests in headless mode
  
