stages:
  - test

cypress:
  stage: test
  image: node16
  script:
    - cd frontend # Change to the frontend directory where your Cypress tests are located
    - npm install --legacy-peer-deps
    - npm start &
    - npx cypress run  # This command will run all Cypress tests in headless mode
  
