services:
  front-end:
    container_name: gamesitefront
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes: 
      - ./

  back-end:
    container_name: gamesiteback
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./server
    environment:
      - DATABASE_ACCESS=mongodb+srv://brendanewen16:3BmFyuA4alqoB666@cluster0.3mfmcng.mongodb.net/?retryWrites=true&w=majority
      - SECRET_KEY=Zz47H.Aa5B